### PR TITLE
Rerun tests

### PR DESCRIPTION
**Pull request by tpgxyz**
@itchka @fedya @berolinux Please review this, as ABF needs this asap.

### CODE REVIEW

**Comment by itchka** [comment]
TPG; I could be worng here but shouldn't urpmi have the rpms to install as the last item on the command line. https://github.com/OpenMandrivaSoftware/docker-builder/blob/master/build-rpm.sh#L293

**Comment by itchka** [comment]
TPG; Again only going by what I have read and learn't from tutorials "ls" is not recommended for generating lists of commands to feed to programs. Apparently find is preferred see answer 4 here
https://stackoverflow.com/questions/13830036/difference-between-using-ls-and-find-to-loop-over-files-in-a-bash-script

**Comment by itchka** [comment]
MAX_RETRIES=10..... I may have misunderstood the code but it does look to me as if the tests return anything but zero they will be run again. Seems a bit like flogging a dead horse to me.  I think the only time we would want to retry is if the repo was updated in the middle otherwise it's down to the developer to start the test again.

**Comment by tpgxyz** [comment]
@itchka  your comments are for "master" branch not "rerun tests". Yo can add your comments in this PR in "files changed" tab.

MAX_RETRIES is is valid when $RETRY_GREP_STR strin is met in urpmi logs.

"find" is way more bigger than "ls" and script is parsing directory for "few" files not for zounds.

**Review by itchka — COMMENTED** [review]
Maybe a few comments to indicate from where data for the variables originates. 
Is it really necessary to test the src rpm? surely that has already been tested by the act of building the package in the first place. From the logs it seems we are installing all the compiler and development packages which makes the test process much longer as well as using up bandwidth. Otherwise It all looks ok to my inexepert eye.

**Pull request merged**
